version: '3.2'

services:
  postgres:
      image: postgres:11
      ports:
          - "5432:5432"
      env_file:
        - .env

  aiohttp:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    volumes:
      - ./vehicle_builder:/app
    ports:
      - "80:8000"
    env_file:
      - .env
