version: '3.2'

services:
  postgres:
      image: postgres:11
      ports:
          - "5432:5432"
      env_file:
        - .env

  aiohttp:
    build:
      dockerfile: Dockerfile
      context: .
    command: >
      bash -c "while ! curl http://postgres:5432/ 2>&1 | grep '52'; do sleep 1; done; 
      python3 main.py"
    depends_on:
      - postgres
    ports:
      - "80:8000"
    env_file:
      - .env
